### ISSUE TITLE
Usage with klipper_z_calibration

### ISSUE THREAD

**Issue by loopj** [nielsvz/klipper_dockable_probe#1]
Do you have this working with the klipper z calibration plugin?

I'm using the latest version of both this and klipper_z_calibration and seeing `Probe switch not closed - Probe not attached?` when running `CALIBRATE_Z` after the probe moves to the middle of the bed.

It looks like a check was added to klipper_z_calibration which calls `QUERY_PROBE` internally:
https://github.com/protoloft/klipper_z_calibration/commit/2eb689b4e6e9cb7e3e325d020426f96ac77a614a

`QUERY_PROBE` returns `TRIGGERED` in every state (probe docked, not docked, docked and pressed).

Just curious to see if you have this working

**Comment by nielsvz** [comment]
I am using both the dockable probe and Z calibration plugins. My configuration can be found here: https://github.com/nielsvz/klipper-configuration/blob/main/voron-2/config/homing.cfg

In certain cases, having a default bed mesh saved can interfere with the homing routine of my printers, even if I clear the mesh before homing.

**Comment by loopj** [comment]
Thanks @nielsvz! I was actually referencing your fantastic configuration setup already, thanks for sharing it.

I just confirmed that this problem goes away if I downgrade my klipper_z_calibration script to before that commit, so beware if you upgrade.
